//------------------------------------------------------------------------------
// <auto-generated>
//     This file has been simplified to remove VSTO dependencies
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordOverlayProofreader.Addin {
    
    
    /// 
    [global::System.Runtime.InteropServices.GuidAttribute("FD050364-6792-4326-919D-903160612467")]
    [global::System.ComponentModel.DescriptionAttribute("WordOverlayProofreader.Addin")]
    public sealed partial class ThisAddIn {
        
        // Simplified - no VSTO infrastructure needed
    }
}
